SOURCES=$(wildcard *.tex)
TARGETS=$(patsubst %.tex,%.pdf,$(SOURCES))
GITINFOS=$(patsubst %.tex,%.gitinfo,$(SOURCES))

%.gitinfo: .git/logs/HEAD
	@echo "%%% This file is generated by Makefile." > $@.new
	@echo "%%% Do not edit this file!%%%" >> $@.new
	@git log -1 --format="format:\\gdef\\gitHash{%H}\\gdef\\gitAbbrevHash{%h}\\gdef\\gitAuthorDate{%as}\\gdef\\gitAuthorIsoDate{%ad}\\gdef\\gitAuthorName{%an}" $(patsubst %.gitinfo,%.tex,$@) >> $@.new
	@if ! diff $@ $@.new &> /dev/null; then mv $@.new $@; else rm $@.new; fi

%.pdf: %.tex %.gitinfo *.sty uebung_cs.cls
	latexmk $<

.PHONY: all
all: $(TARGETS)

.PHONY: gitinfo
gitinfo: $(GITINFOS)

.PHONY: clean
clean:
	rm -f *.gitinfo *.gitinfo.new
	latexmk -C
